In [30]:
import numpy as np
import pandas as pd

pd.__version__

'1.4.2'

In [4]:
#import wget

In [28]:
# !wget -P ../data/ https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
# df = pd.read_csv('../data/laptops.csv', encoding='latin-1')
# df.head()

--2024-09-20 09:43:01--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: '../data/laptops.csv'

     0K .......... .......... .......... .......... .......... 17%  158K 2s
    50K .......... .......... .......... .......... .......... 34% 61.7K 2s
   100K .......... .......... .......... .......... .......... 51%  366K 1s
   150K .......... .......... .......... .......... .......... 68%  197K 1s
   200K .......... .......... .......... .......... .......... 85%  286K 0s
   250K .......... .......... .......... .......... .         100%  805K=1.7s

2024-09-20 09:43:04 (167 KB/s) - '../data/laptops.csv' saved [298573/298573]



Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [8]:
#!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv


--2024-09-20 09:02:44--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: 'laptops.csv'

     0K .......... .......... .......... .......... .......... 17% 32.1K 8s
    50K .......... .......... .......... .......... .......... 34% 80.3K 4s
   100K .......... .......... .......... .......... .......... 51%  151K 2s
   150K .......... .......... .......... .......... .......... 68% 49.8K 2s
   200K .......... .......... .......... .......... .......... 85% 29.1K 1s
   250K .......... .......... .......... .......... .         100%  319K=5.4s

2024-09-20 09:03:09 (54.4 KB/s) - 'laptops.csv' saved [298573/298573]



In [2]:
df = pd.read_csv('laptops.csv')
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

#### Q2 RECORDS COUNT

In [3]:
df.shape

(2160, 12)

   #### Q3 Laptop brands

In [4]:
df['Brand'].unique()

array(['Asus', 'Alurin', 'MSI', 'HP', 'Lenovo', 'Medion', 'Acer', 'Apple',
       'Razer', 'Gigabyte', 'Dell', 'LG', 'Samsung', 'PcCom', 'Microsoft',
       'Primux', 'Prixton', 'Dynabook Toshiba', 'Thomson', 'Denver',
       'Deep Gaming', 'Vant', 'Innjoo', 'Jetwing', 'Millenium', 'Realme',
       'Toshiba'], dtype=object)

In [5]:
df['Brand'].nunique()

27

In [6]:
df['Brand'].count()

2160

#### Q4. Missing values

In [7]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

#### Q5. Maximum final price of Dell

In [8]:
dellmax = df[df['Brand'] == 'Dell']
dellmax.head()

Laptop Status Brand     Model  \
161  Dell Vostro 3510 Intel Core i3-1115G4/8 GB/256...    New  Dell    Vostro   
271  Dell Vostro 3510 Intel Core i5-1135G7/8 GB/256...    New  Dell    Vostro   
281  Dell Vostro 3520 Intel Core i7-1255U/16GB/512G...    New  Dell    Vostro   
319  Dell Latitude 3520 Intel Core i5-1135G7/8GB/25...    New  Dell  Latitude   
328  Dell Vostro 3510 Intel Core i5-1135G7/16 GB/51...    New  Dell    Vostro   

               CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
161  Intel Core i3    8      256          SSD  NaN    15.6    No       599.00  
271  Intel Core i5    8      256          SSD  NaN    15.6    No       690.15  
281  Intel Core i7   16      512          SSD  NaN    15.6    No       889.00  
319  Intel Core i5    8      256          SSD  NaN    15.6    No       789.00  
328  Intel Core i5   16      512          SSD  NaN    15.6    No       869.00

In [9]:
dellmax['Final Price'].max()

3936.0

#### Q6. Median value of Screen Column

In [10]:
# MEDIAN

df['Screen'].median()

15.6

In [11]:
# MOST FREQUENT

df['Screen'].mode()

0    15.6
Name: Screen, dtype: float64

In [12]:
df = df.fillna(value = df['Screen'].median(), axis = 0)

In [13]:
df.isnull().sum()

Laptop          0
Status          0
Brand           0
Model           0
CPU             0
RAM             0
Storage         0
Storage type    0
GPU             0
Screen          0
Touch           0
Final Price     0
dtype: int64

In [14]:
# NEW MEDIAN

df['Screen'].median()

15.6

#### Q7. Sum of weights

Select all the "Innjoo" laptops from the dataset.

Select only columns RAM, Storage, Screen.

Get the underlying NumPy array. Let's call it X.

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

Compute the inverse of XTX.

Create an array y with values [1100, 1300, 800, 900, 1000, 1100].

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

What's the sum of all the elements of the result?

In [20]:
innjoo = df[df['Brand'] == 'Innjoo']
innjoo#.head()

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type   GPU  Screen Touch  \
1478  Intel Celeron    8      256          SSD  15.6    15.6    No   
1479  Intel Celeron    8      512          SSD  15.6    15.6    No   
1480  Intel Celeron    4       64         eMMC  15.6    14.1    No   
1481  Intel Celeron    6       64         eMMC  15.6    14.1    No   
1482  Intel Celeron    6      128          SSD  15.6    14.1    No   
1483  Intel Celeron    6      128         eMMC  15.6    14.1    No   

      Final Price  
1478       311.37  
1479       392.55  
1480       251.40  
1481       383.61  
1482       317.02  
1483       431.38

In [19]:
innjoo.shape

(6, 12)

In [23]:
# Selecting only columns RAM, Storage, Screen.

innjoo = innjoo[['RAM', 'Storage', 'Screen']]
innjoo

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [24]:
# Conver innjoo to a numpy array

X = innjoo.to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [28]:
# Matrix multiplication between X transpose (X.T) and X

# X transpose
XT = X.T
XT

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [31]:
# matrix multiplication XT.X

XTX = np.matmul(XT,X)

XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [32]:
# Inverse of XTX

XTX_Inv = np.linalg.inv(XTX)
XTX_Inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [33]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [35]:
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

Z = np.matmul(XTX_Inv, XT)

Z

array([[ 0.26298349, -0.12560233, -0.40646389,  0.14958687,  0.05244042,
         0.05244042],
       [-0.00110155,  0.00295059,  0.00125892, -0.00177691, -0.00076387,
        -0.00076387],
       [-0.08772226,  0.0269791 ,  0.17140891, -0.0302108 , -0.00153546,
        -0.00153546]])

In [37]:
w = np.matmul(Z,y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [38]:
#  sum of all the elements of w

sum_w = np.sum(w)
sum_w

91.29988062995815