## CREATING ARRAYS

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\HP\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 200)

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [11]:
# converting a list to array
lst = [1,2,3,4,5]
a = np.array(lst)

a

array([1, 2, 3, 4, 5])

In [12]:
#Access an element in the array

a[1]

2

In [13]:
a[1] = 100
a

array([  1, 100,   3,   4,   5])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# to create a range of numbers

#by default it starts from 0
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
# we can specify the number it starts from

np.arange(4, 16)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [26]:
# linspace creates an array filled with numbers between the first and second parameter

np.linspace(0, 500, 10)

array([  0.        ,  55.55555556, 111.11111111, 166.66666667,
       222.22222222, 277.77777778, 333.33333333, 388.88888889,
       444.44444444, 500.        ])

### MULTIDIMENSIONAL ARRAYS

In [27]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [33]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ])

In [35]:
# to select an item in [row, column]

n[1,2]

6

In [37]:
# To change an item in column

n[1,2] = 30
n

array([[ 1,  2,  3],
       [ 4,  5, 30],
       [ 7,  8,  9]])

In [40]:
#To change an entire row

n[2] = [1,1,1]

In [41]:
n

array([[ 1,  2,  3],
       [ 4,  5, 30],
       [ 1,  1,  1]])

In [43]:
# To select a column

n[:, 2]

array([ 3, 30,  1])

In [44]:
# To change a column

n[:, 2] = [12,11,14]

In [45]:
n

array([[ 1,  2, 12],
       [ 4,  5, 11],
       [ 1,  1, 14]])

## Randomly generated arrays

In [56]:
np.random.rand(5,2)

array([[0.62113383, 0.52914209],
       [0.13457995, 0.51357812],
       [0.18443987, 0.78533515],
       [0.85397529, 0.49423684],
       [0.84656149, 0.07964548]])

In [57]:
# use seed to fix the randomly generated values

np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [60]:
# standard normal distribution RANDN

np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [62]:
# to make the values between 0 and 100, multiply by 100

np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [64]:
# to generate integers

np.random.randint(low = 5, high = 100, size= (5,2))

array([[42, 44],
       [72,  9],
       [47, 56],
       [43, 38],
       [63, 72]])

## Element wise operation

In [66]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [67]:
b + 1

array([1, 2, 3, 4, 5])

In [68]:
# chaining operations

b = (b *2 +10) **2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [69]:
c = a + b

In [70]:
c

array([  2.  , 101.44,   4.96,   6.56,   8.24])

In [71]:
d = (a + b)/30
d

array([0.06666667, 3.38133333, 0.16533333, 0.21866667, 0.27466667])

## Comparison operators

In [72]:
a

array([  1, 100,   3,   4,   5])

In [73]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [74]:
a >= 3

array([False,  True,  True,  True,  True])

In [77]:
a < c

array([ True,  True,  True,  True,  True])

In [82]:
# returns the values/elements that are true

a[a >= b]

array([  1, 100,   3,   4,   5])

In [83]:
a >= b

array([ True,  True,  True,  True,  True])

## Summarizing operators

In [84]:
a.min()

1

In [85]:
b.max()

3.24

In [86]:
d.std()

1.2818353508413887

In [88]:
n.max()

14

In [89]:
n.sum()

51